export const REGISTER_REQUEST_PENDING = "REGISTER_REQUEST_PENDING";
export const REGISTER_REQUEST_ERROR = "REGISTER_REQUEST_ERROR";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";

export const LOGIN_REQUEST_PENDING = "LOGIN_REQUEST_PENDING";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";

export const RESET_PASSWORD_REQUEST_PENDING = "RESET_PASSWORD_REQUEST_PENDING";
export const RESET_PASSWORD_REQUEST_ERROR = "RESET_PASSWORD_REQUEST_ERROR";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";

export const CHANGE_PASSWORD_REQUEST_PENDING = "CHANGE_PASSWORD_REQUEST_PENDING";
export const CHANGE_PASSWORD_REQUEST_ERROR = "CHANGE_PASSWORD_REQUEST_ERROR";
export const CHANGE_PASSWORD_REQUEST_SUCCESS = "CHANGE_PASSWORD_REQUEST_SUCCESS";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

export const GET_USER_INFO_REQUEST_PENDING = "GET_USER_INFO_REQUEST_PENDING";
export const GET_USER_INFO_REQUEST_ERROR = "GET_USER_INFO_REQUEST_ERROR";
export const GET_USER_INFO_REQUEST_SUCCESS = "GET_USER_INFO_REQUEST_SUCCESS";